AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - vendor/bundle/**/*
    - munge.gemspec
    - sandbox/**/*
  DisplayCopNames: true

Metrics/AbcSize:
  Exclude:
    - test/**/*

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Max: 15
  Exclude:
    - test/**/*

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/ClassLength:
  Exclude:
    - test/**/*

Style/AccessorMethodName:
  Exclude:
    - lib/munge/go/**/*

Style/AlignParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ExtraSpacing:
  AllowForAlignment: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/NegatedIf:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 6

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SpaceAroundOperators:
  AllowForAlignment: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
