AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - vendor/bundle/**/*
    - Gemfile
    - Rakefile
    - munge.gemspec
    - sandbox/**/*

Metrics/AbcSize:
  Exclude:
    - test/**/*

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15
  Exclude:
    - test/**/*

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/ClassLength:
  Exclude:
    - test/**/*

Style/AccessorMethodName:
  Exclude:
    - lib/munge/go/**/*

Style/AlignParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/NegatedIf:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - seeds/**/*

Style/UnneededInterpolation:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'
  Enabled: true

Style/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
