language: ruby
rvm:
  - 2.4.0
  - 2.3.0
  - 2.2
  - 2.1
  - ruby-head
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
script: ./script/test
addons:
  code_climate:
    repo_token: b8fc4a1660d2067059476e3e579080fb6820daedbdb5e56cd9028f5dcc058fc8
notifications:
  email: false
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
