source: src
output: dest
data: data.yml
layouts: layouts
index: index.html
fingeprint_separator: "-"
text_extensions:
  - html
  - htm
  - txt
  - md
bintext_extensions:
  - js
  - css
  - scss
bin_extensions:
  - gif
  - ico
  - jpg
  - jpeg
  - png
  - otf
  - ttf
  - eot
  - woff
dynamic_extensions:
  - erb
  - scss
  - md
