source: src
output: dest
data: data.yml
layouts: layouts
index: index.html
fingeprint_separator: "-"
text_extensions:
  - html
  - htm
  - txt
  - md
ignored_basenames:
  - index
keep_extensions:
  - gif
  - ico
  - jpg
  - jpeg
  - png
  - css
  - js
